services:
  app:
    image: yanbpenalva/miniworld-app:latest
    container_name: miniworld-app
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      CHOKIDAR_USEPOLLING: "true"
      PHP_ENABLE_XDEBUG: "1"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - miniworld-app-network

  nginx:
    image: nginx:1.27.4-alpine
    container_name: miniworld-app-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./docker/NGINX/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started
    networks:
      - miniworld-app-network

  db:
    image: postgres:16.8
    container_name: miniworld-app-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: miniworld-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/PGSQL/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d miniworld-app" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - miniworld-app-network

  redis:
    image: redis:7.2.4-alpine
    container_name: miniworld-app-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - miniworld-app-network

  mailpit:
    image: axllent/mailpit:v1.15.1
    container_name: miniworld-app-mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - miniworld-app-network

volumes:
  pg_data:
    driver: local

networks:
  miniworld-app-network:
    driver: bridge
