services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: miniworld-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - miniworld-app-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.27.4-alpine
    container_name: miniworld-app-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/NGINX/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - miniworld-app-network

  db:
    image: postgres:16.8
    container_name: miniworld-app-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - miniworld-app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine
    container_name: miniworld-app-redis
    restart: always
    networks:
      - miniworld-app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local

networks:
  miniworld-app-network:
    driver: bridge
